/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonacionesRouteImport } from './routes/donaciones'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as ComedorIdRouteImport } from './routes/comedor.$id'
import { Route as CampanaIdRouteImport } from './routes/campana.$id'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPanelIndexRouteImport } from './routes/_authenticated/panel.index'
import { Route as AuthenticatedPanelReservasRouteImport } from './routes/_authenticated/panel.reservas'
import { Route as AuthenticatedPanelPersonalRouteImport } from './routes/_authenticated/panel.personal'
import { Route as AuthenticatedPanelPerfilRouteImport } from './routes/_authenticated/panel.perfil'
import { Route as AuthenticatedPanelPadronRouteImport } from './routes/_authenticated/panel.padron'
import { Route as AuthenticatedPanelMenuRouteImport } from './routes/_authenticated/panel.menu'
import { Route as AuthenticatedPanelMasRouteImport } from './routes/_authenticated/panel.mas'
import { Route as AuthenticatedPanelInsumosRouteImport } from './routes/_authenticated/panel.insumos'
import { Route as AuthenticatedPanelCronogramaRouteImport } from './routes/_authenticated/panel.cronograma'
import { Route as AuthenticatedPanelCampanasRouteImport } from './routes/_authenticated/panel.campanas'
import { Route as AuthenticatedPanelCajaRouteImport } from './routes/_authenticated/panel.caja'

const DonacionesRoute = DonacionesRouteImport.update({
  id: '/donaciones',
  path: '/donaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ComedorIdRoute = ComedorIdRouteImport.update({
  id: '/comedor/$id',
  path: '/comedor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanaIdRoute = CampanaIdRouteImport.update({
  id: '/campana/$id',
  path: '/campana/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelIndexRoute = AuthenticatedPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPanelRoute,
} as any)
const AuthenticatedPanelReservasRoute =
  AuthenticatedPanelReservasRouteImport.update({
    id: '/reservas',
    path: '/reservas',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelPersonalRoute =
  AuthenticatedPanelPersonalRouteImport.update({
    id: '/personal',
    path: '/personal',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelPerfilRoute =
  AuthenticatedPanelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelPadronRoute =
  AuthenticatedPanelPadronRouteImport.update({
    id: '/padron',
    path: '/padron',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelMenuRoute = AuthenticatedPanelMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedPanelRoute,
} as any)
const AuthenticatedPanelMasRoute = AuthenticatedPanelMasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => AuthenticatedPanelRoute,
} as any)
const AuthenticatedPanelInsumosRoute =
  AuthenticatedPanelInsumosRouteImport.update({
    id: '/insumos',
    path: '/insumos',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelCronogramaRoute =
  AuthenticatedPanelCronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelCampanasRoute =
  AuthenticatedPanelCampanasRouteImport.update({
    id: '/campanas',
    path: '/campanas',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelCajaRoute = AuthenticatedPanelCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedPanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donaciones': typeof DonacionesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/panel': typeof AuthenticatedPanelRouteWithChildren
  '/campana/$id': typeof CampanaIdRoute
  '/comedor/$id': typeof ComedorIdRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/panel/caja': typeof AuthenticatedPanelCajaRoute
  '/panel/campanas': typeof AuthenticatedPanelCampanasRoute
  '/panel/cronograma': typeof AuthenticatedPanelCronogramaRoute
  '/panel/insumos': typeof AuthenticatedPanelInsumosRoute
  '/panel/mas': typeof AuthenticatedPanelMasRoute
  '/panel/menu': typeof AuthenticatedPanelMenuRoute
  '/panel/padron': typeof AuthenticatedPanelPadronRoute
  '/panel/perfil': typeof AuthenticatedPanelPerfilRoute
  '/panel/personal': typeof AuthenticatedPanelPersonalRoute
  '/panel/reservas': typeof AuthenticatedPanelReservasRoute
  '/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donaciones': typeof DonacionesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campana/$id': typeof CampanaIdRoute
  '/comedor/$id': typeof ComedorIdRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/panel/caja': typeof AuthenticatedPanelCajaRoute
  '/panel/campanas': typeof AuthenticatedPanelCampanasRoute
  '/panel/cronograma': typeof AuthenticatedPanelCronogramaRoute
  '/panel/insumos': typeof AuthenticatedPanelInsumosRoute
  '/panel/mas': typeof AuthenticatedPanelMasRoute
  '/panel/menu': typeof AuthenticatedPanelMenuRoute
  '/panel/padron': typeof AuthenticatedPanelPadronRoute
  '/panel/perfil': typeof AuthenticatedPanelPerfilRoute
  '/panel/personal': typeof AuthenticatedPanelPersonalRoute
  '/panel/reservas': typeof AuthenticatedPanelReservasRoute
  '/panel': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/donaciones': typeof DonacionesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRouteWithChildren
  '/campana/$id': typeof CampanaIdRoute
  '/comedor/$id': typeof ComedorIdRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/_authenticated/panel/caja': typeof AuthenticatedPanelCajaRoute
  '/_authenticated/panel/campanas': typeof AuthenticatedPanelCampanasRoute
  '/_authenticated/panel/cronograma': typeof AuthenticatedPanelCronogramaRoute
  '/_authenticated/panel/insumos': typeof AuthenticatedPanelInsumosRoute
  '/_authenticated/panel/mas': typeof AuthenticatedPanelMasRoute
  '/_authenticated/panel/menu': typeof AuthenticatedPanelMenuRoute
  '/_authenticated/panel/padron': typeof AuthenticatedPanelPadronRoute
  '/_authenticated/panel/perfil': typeof AuthenticatedPanelPerfilRoute
  '/_authenticated/panel/personal': typeof AuthenticatedPanelPersonalRoute
  '/_authenticated/panel/reservas': typeof AuthenticatedPanelReservasRoute
  '/_authenticated/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/donaciones'
    | '/admin'
    | '/panel'
    | '/campana/$id'
    | '/comedor/$id'
    | '/invitacion/$token'
    | '/panel/caja'
    | '/panel/campanas'
    | '/panel/cronograma'
    | '/panel/insumos'
    | '/panel/mas'
    | '/panel/menu'
    | '/panel/padron'
    | '/panel/perfil'
    | '/panel/personal'
    | '/panel/reservas'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/donaciones'
    | '/admin'
    | '/campana/$id'
    | '/comedor/$id'
    | '/invitacion/$token'
    | '/panel/caja'
    | '/panel/campanas'
    | '/panel/cronograma'
    | '/panel/insumos'
    | '/panel/mas'
    | '/panel/menu'
    | '/panel/padron'
    | '/panel/perfil'
    | '/panel/personal'
    | '/panel/reservas'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/donaciones'
    | '/_authenticated/admin'
    | '/_authenticated/panel'
    | '/campana/$id'
    | '/comedor/$id'
    | '/invitacion/$token'
    | '/_authenticated/panel/caja'
    | '/_authenticated/panel/campanas'
    | '/_authenticated/panel/cronograma'
    | '/_authenticated/panel/insumos'
    | '/_authenticated/panel/mas'
    | '/_authenticated/panel/menu'
    | '/_authenticated/panel/padron'
    | '/_authenticated/panel/perfil'
    | '/_authenticated/panel/personal'
    | '/_authenticated/panel/reservas'
    | '/_authenticated/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DonacionesRoute: typeof DonacionesRoute
  CampanaIdRoute: typeof CampanaIdRoute
  ComedorIdRoute: typeof ComedorIdRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donaciones': {
      id: '/donaciones'
      path: '/donaciones'
      fullPath: '/donaciones'
      preLoaderRoute: typeof DonacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedor/$id': {
      id: '/comedor/$id'
      path: '/comedor/$id'
      fullPath: '/comedor/$id'
      preLoaderRoute: typeof ComedorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campana/$id': {
      id: '/campana/$id'
      path: '/campana/$id'
      fullPath: '/campana/$id'
      preLoaderRoute: typeof CampanaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/': {
      id: '/_authenticated/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof AuthenticatedPanelIndexRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/reservas': {
      id: '/_authenticated/panel/reservas'
      path: '/reservas'
      fullPath: '/panel/reservas'
      preLoaderRoute: typeof AuthenticatedPanelReservasRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/personal': {
      id: '/_authenticated/panel/personal'
      path: '/personal'
      fullPath: '/panel/personal'
      preLoaderRoute: typeof AuthenticatedPanelPersonalRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/perfil': {
      id: '/_authenticated/panel/perfil'
      path: '/perfil'
      fullPath: '/panel/perfil'
      preLoaderRoute: typeof AuthenticatedPanelPerfilRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/padron': {
      id: '/_authenticated/panel/padron'
      path: '/padron'
      fullPath: '/panel/padron'
      preLoaderRoute: typeof AuthenticatedPanelPadronRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/menu': {
      id: '/_authenticated/panel/menu'
      path: '/menu'
      fullPath: '/panel/menu'
      preLoaderRoute: typeof AuthenticatedPanelMenuRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/mas': {
      id: '/_authenticated/panel/mas'
      path: '/mas'
      fullPath: '/panel/mas'
      preLoaderRoute: typeof AuthenticatedPanelMasRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/insumos': {
      id: '/_authenticated/panel/insumos'
      path: '/insumos'
      fullPath: '/panel/insumos'
      preLoaderRoute: typeof AuthenticatedPanelInsumosRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/cronograma': {
      id: '/_authenticated/panel/cronograma'
      path: '/cronograma'
      fullPath: '/panel/cronograma'
      preLoaderRoute: typeof AuthenticatedPanelCronogramaRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/campanas': {
      id: '/_authenticated/panel/campanas'
      path: '/campanas'
      fullPath: '/panel/campanas'
      preLoaderRoute: typeof AuthenticatedPanelCampanasRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/caja': {
      id: '/_authenticated/panel/caja'
      path: '/caja'
      fullPath: '/panel/caja'
      preLoaderRoute: typeof AuthenticatedPanelCajaRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
  }
}

interface AuthenticatedPanelRouteChildren {
  AuthenticatedPanelCajaRoute: typeof AuthenticatedPanelCajaRoute
  AuthenticatedPanelCampanasRoute: typeof AuthenticatedPanelCampanasRoute
  AuthenticatedPanelCronogramaRoute: typeof AuthenticatedPanelCronogramaRoute
  AuthenticatedPanelInsumosRoute: typeof AuthenticatedPanelInsumosRoute
  AuthenticatedPanelMasRoute: typeof AuthenticatedPanelMasRoute
  AuthenticatedPanelMenuRoute: typeof AuthenticatedPanelMenuRoute
  AuthenticatedPanelPadronRoute: typeof AuthenticatedPanelPadronRoute
  AuthenticatedPanelPerfilRoute: typeof AuthenticatedPanelPerfilRoute
  AuthenticatedPanelPersonalRoute: typeof AuthenticatedPanelPersonalRoute
  AuthenticatedPanelReservasRoute: typeof AuthenticatedPanelReservasRoute
  AuthenticatedPanelIndexRoute: typeof AuthenticatedPanelIndexRoute
}

const AuthenticatedPanelRouteChildren: AuthenticatedPanelRouteChildren = {
  AuthenticatedPanelCajaRoute: AuthenticatedPanelCajaRoute,
  AuthenticatedPanelCampanasRoute: AuthenticatedPanelCampanasRoute,
  AuthenticatedPanelCronogramaRoute: AuthenticatedPanelCronogramaRoute,
  AuthenticatedPanelInsumosRoute: AuthenticatedPanelInsumosRoute,
  AuthenticatedPanelMasRoute: AuthenticatedPanelMasRoute,
  AuthenticatedPanelMenuRoute: AuthenticatedPanelMenuRoute,
  AuthenticatedPanelPadronRoute: AuthenticatedPanelPadronRoute,
  AuthenticatedPanelPerfilRoute: AuthenticatedPanelPerfilRoute,
  AuthenticatedPanelPersonalRoute: AuthenticatedPanelPersonalRoute,
  AuthenticatedPanelReservasRoute: AuthenticatedPanelReservasRoute,
  AuthenticatedPanelIndexRoute: AuthenticatedPanelIndexRoute,
}

const AuthenticatedPanelRouteWithChildren =
  AuthenticatedPanelRoute._addFileChildren(AuthenticatedPanelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DonacionesRoute: DonacionesRoute,
  CampanaIdRoute: CampanaIdRoute,
  ComedorIdRoute: ComedorIdRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
